language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"

os:
  - linux
  - osx

env:
  - RR="--durations=10"
  - RR=""

# OSx seems to fail for the moment
matrix:
  allow_failures:
      - os: osx

# command to install dependencies
install: 
 - pip install coveralls
# command to run tests
script: 
  - py.test $RR megaracte
after_success:
  - coveralls
