language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"

os:
  - linux
  - osx

env:
  - RR="--durations=10"
  - RR=""

matrix:
  fast_finish: true
  include:
   - python: 2.7
     os: linux
     env: COVERAGE=true

# OSx seems to fail for the moment
matrix:
  allow_failures:
   - os: osx

# command to install dependencies
install: 
 - if [[ $COVERAGE == true ]]; then pip install coveralls; fi
# command to run tests
script: 
  - py.test $RR megaracte
  - if [[ $COVERAGE == true ]]; then coverage run --source numina -m py.test; fi
after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
